$kind: http-request
url: "{{base_url}}/api/jobs/company/jobs/applications/{{application_id}}/"
method: PATCH
headers:
  Content-Type: application/json
  Authorization: CompanyToken {{company_token}}
body:
  type: text
  content: |-
    {
      "status": "reviewed"
    }
order: 8000
