# Generated by Django 5.2.13 on 2026-08-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobposting_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="minimum_experience",
            field=models.PositiveIntegerField(
                default=0, help_text="الحد الأدنى لسنوات الخبرة المطلوبة"
            ),
        ),
    ]
