# Generated by Django 5.2.13 on 2026-08-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobposting_minimum_experience"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobposting",
            name="minimum_experience",
        ),
    ]
