# Generated by Django 5.2.13 on 2026-08-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_jobposting_minimum_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="embedding",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
