# Generated by Django 5.2.13 on 2026-08-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_jobposting_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="skills_embedding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
